[loader]
entrypoint = "file:/usr/lib/x86_64-linux-gnu/gramine/libsysdb.so"
log_level = "error"
insecure__use_cmdline_argv = true

[libos]
entrypoint = "/usr/bin/python3.8"

[sys]
enable_sigterm_injection = true
enable_extra_runtime_domain_names_conf = true

[fs]
[[fs.mounts]]
path = "/lib"
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc"

[[fs.mounts]]
path = "/lib/x86_64-linux-gnu"
uri = "file:/lib/x86_64-linux-gnu"

[[fs.mounts]]
path = "/usr/lib/x86_64-linux-gnu"
uri = "file:/usr/lib/x86_64-linux-gnu"

[[fs.mounts]]
path = "/usr"
uri = "file:/usr"

[[fs.mounts]]
path = "/etc"
uri = "file:/etc"

[[fs.mounts]]
type = "tmpfs"
path = "/tmp"

[sgx]
debug = true
nonpie_binary = true
enclave_size = "1G"
max_threads = 32
remote_attestation = "none"
ra_client_spid = ""
ra_client_linkable = false
thread_num = 4
isvprodid = 0
isvsvn = 0
require_avx = false
require_avx512 = false
require_mpx = false
require_pkru = false
require_amx = false
support_exinfo = false
enable_stats = false

[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/libsysdb.so"

[[sgx.trusted_files]]
uri = "file:/usr/bin/python3.8"

[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/"

[[sgx.trusted_files]]
uri = "file:/lib/x86_64-linux-gnu/"

[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/"

[[sgx.trusted_files]]
uri = "file:/usr"

[[sgx.trusted_files]]
uri = "file:/etc"

[[sgx.trusted_files]]
uri = "file:scripts/"

[[sgx.trusted_files]]
uri = "file:compile.py"

[[sgx.trusted_files]]
uri = "file:helper-files/"

[loader.env]
LD_LIBRARY_PATH = "/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu"
OMP_NUM_THREADS = "4"

[sys.stack]
size = "2M"
